spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.30.3.95:1521/orcl
    username: c##1901208
    password: p1901208
  devtools:
    remote:
      restart:
        enabled: true

#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: sewoon
#    password: 1234
#  devtools:
#    remote:
#      restart:
#        enabled: true




server:
  port: 8000

mybatis:
  mapper-locations: mybatis/**.xml
  config-location: classpath:mybatis-config.xml
