spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: insa
    password: insa
  devtools:
    remote:
      restart:
        enabled: true


server:
  port: 8000

mybatis:
  type-aliases-package: c.e.exper.data
  mapper-locations : mybatis/**.xml
  config-location: classpath:mybatis-config.xml